Initial implementation of Loggly service
tidepool-org/LogglyService pull request #2
Opened 2019-09-24 05:18 UTC by darinkrauss

- Implement Service and ServiceUI protocols
- Implement Logging protocol
- Connect with Loggly third-party service

https://tidepool.atlassian.net/browse/LOOP-22

2019-09-24 16:44 UTC, nhamming submitted a review, later dismissed
Similar comments as amplitude. If you agree with them, then consider them here as well. 

Otherwise LGTM.

2019-09-30 16:58 UTC, nhamming submitted a review, later dismissed
+1

2019-10-03 12:13 UTC, nhamming submitted a review, later dismissed
+1

2019-10-04 21:07 UTC, ps2 requested changes

2019-10-04 21:07 UTC, ps2 commented on LogglyServiceKitUI/LogglyServiceTableViewController.swift
> +            message: NSLocalizedString("Are you sure you want to delete this service?", comment: "Confirmation message for deleting a service"),
NSLocalizedString -> LocalizedString

2019-10-05 16:53 UTC, ps2 approved these changes
🎉 LGTM!

2019-10-07 16:17 UTC, merged